# -*- coding: utf-8 -*-
"""stock_portfolio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fXFiCzwXMiICC7vuIpGHqc_8X2UFlMCU
"""

import datetime as dt
import pandas as pd
import matplotlib.pyplot as plt
import pandas_datareader as web

!pip install --upgrade pandas
!pip install --upgrade pandas-datareader

ticker = ['AAPL','TSLA','FB',"NVDA",'SBIN.NS']
amount = [100,50,50,200,400]
prices = []
total = []


for i in ticker:
  df = web.DataReader(i,'yahoo',dt.datetime(2019,1,1),dt.datetime.now())
  price = df[-1:]['Close'][0]
  prices.append(price)
  index = ticker.index(i)
  total.append(price*amount[index])

fig,ax = plt.subplots(figsize=(16,8))

ax.set_facecolor('black')
ax.figure.set_facecolor('#121212')

ax.tick_params(axis='x',color='white')
ax.tick_params(axis='y',color='white')

ax.set_title('PORTFOLIO VISUALIZER',color='#EF6C35',fontsize=20)
_,text,_=ax.pie(total,labels=ticker,autopct="%1.1f%%",pctdistance=0.8)
[texts.set_color('white') for texts in text]

my_circle = plt.Circle((0,0),0.55,color='black')
plt.gca().add_artist(my_circle)


plt.show()

